export const HOSPITAL_ID = "00000000-0000-4000-8000-000000000001";

export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS schema_migrations (
    id INT PRIMARY KEY,
    applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS facilities (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    code VARCHAR(60) NOT NULL UNIQUE,
    address TEXT NULL,
    phone VARCHAR(60) NULL,
    email VARCHAR(190) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS profiles (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    display_name VARCHAR(180) NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'Receptionist',
    approval_status VARCHAR(20) NOT NULL DEFAULT 'Approved',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    password_changed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX profiles_facility_role_idx (facility_id, role)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS user_sessions (
    id CHAR(36) PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX user_sessions_user_idx (user_id),
    INDEX user_sessions_expiry_idx (expires_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS counters (
    counter_key VARCHAR(80) PRIMARY KEY,
    counter_value BIGINT NOT NULL DEFAULT 999,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS patients (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    hospital_id VARCHAR(40) NOT NULL UNIQUE,
    lab_id VARCHAR(40) NOT NULL UNIQUE,
    medical_record_number VARCHAR(60) NULL,
    name VARCHAR(200) NOT NULL,
    first_name VARCHAR(100) NULL,
    last_name VARCHAR(100) NULL,
    phone VARCHAR(60) NULL,
    dob DATE NULL,
    date_of_birth DATE NULL,
    sex VARCHAR(20) NULL,
    address TEXT NULL,
    email VARCHAR(190) NULL,
    national_id VARCHAR(100) NULL,
    emergency_contact VARCHAR(190) NULL,
    lga VARCHAR(120) NULL,
    state VARCHAR(120) NULL,
    blood_group VARCHAR(20) NULL,
    genotype VARCHAR(20) NULL,
    allergies TEXT NULL,
    insurance_provider VARCHAR(180) NULL,
    insurance_number VARCHAR(120) NULL,
    ndpr_consent TINYINT(1) NOT NULL DEFAULT 0,
    ndpr_consent_at DATETIME(3) NULL,
    notes TEXT NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX patients_facility_name_idx (facility_id, name),
    INDEX patients_phone_idx (phone)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS tests (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    test_code VARCHAR(40) NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NULL,
    price DECIMAL(12,2) NOT NULL DEFAULT 0,
    result_type VARCHAR(20) NOT NULL DEFAULT 'text',
    reference_range JSON NULL,
    unit VARCHAR(80) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY tests_facility_code_key (facility_id, test_code),
    UNIQUE KEY tests_facility_name_key (facility_id, name)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS test_bundles (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    test_ids JSON NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    usage_count BIGINT NOT NULL DEFAULT 0,
    last_used_at DATETIME(3) NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY test_bundles_name_key (facility_id, name)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS orders (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    patient_id CHAR(36) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Registered',
    priority VARCHAR(30) NOT NULL DEFAULT 'routine',
    notes TEXT NULL,
    ordered_by CHAR(36) NULL,
    ordered_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    reported_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX orders_patient_date_idx (patient_id, ordered_at),
    INDEX orders_status_idx (facility_id, status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS order_tests (
    id CHAR(36) PRIMARY KEY,
    order_id CHAR(36) NOT NULL,
    test_id CHAR(36) NOT NULL,
    specimen_label VARCHAR(200) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Registered',
    sample_code VARCHAR(50) NOT NULL UNIQUE,
    barcode_value VARCHAR(100) NOT NULL,
    qr_value TEXT NOT NULL,
    collected_at DATETIME(3) NULL,
    collected_by CHAR(36) NULL,
    in_progress_at DATETIME(3) NULL,
    results_entered_at DATETIME(3) NULL,
    verified_at DATETIME(3) NULL,
    reported_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY order_tests_order_test_key (order_id, test_id),
    INDEX order_tests_status_idx (status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS sample_custody_logs (
    id CHAR(36) PRIMARY KEY,
    order_test_id CHAR(36) NOT NULL,
    action VARCHAR(80) NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NULL,
    notes TEXT NULL,
    actor_id CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX sample_logs_test_idx (order_test_id, created_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS order_test_results (
    id CHAR(36) PRIMARY KEY,
    order_test_id CHAR(36) NOT NULL UNIQUE,
    value_text TEXT NULL,
    value_numeric DECIMAL(12,4) NULL,
    value_boolean TINYINT(1) NULL,
    interpretation TEXT NULL,
    abnormal_flag TINYINT(1) NOT NULL DEFAULT 0,
    abnormal_reason TEXT NULL,
    entered_by CHAR(36) NULL,
    entered_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    verified_by CHAR(36) NULL,
    verified_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS invoices (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL UNIQUE,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'Unpaid',
    notes TEXT NULL,
    issued_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    due_at DATETIME(3) NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS invoice_items (
    id CHAR(36) PRIMARY KEY,
    invoice_id CHAR(36) NOT NULL,
    order_test_id CHAR(36) NULL UNIQUE,
    test_name VARCHAR(200) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    line_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX invoice_items_invoice_idx (invoice_id)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS invoice_payments (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    invoice_id CHAR(36) NOT NULL,
    receipt_number VARCHAR(60) NOT NULL UNIQUE,
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(80) NOT NULL,
    reference_number VARCHAR(120) NULL,
    notes TEXT NULL,
    received_by CHAR(36) NULL,
    received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX invoice_payments_invoice_idx (invoice_id)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS inventory_items (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NULL,
    unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
    unit VARCHAR(60) NOT NULL DEFAULT 'units',
    lot_number VARCHAR(100) NULL,
    expiry_date DATE NULL,
    reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0,
    vendor VARCHAR(190) NULL,
    storage_location VARCHAR(190) NULL,
    description TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    last_stocked_at DATETIME(3) NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX inventory_name_idx (facility_id, name)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS inventory_transactions (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    item_id CHAR(36) NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL,
    unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
    balance_after DECIMAL(12,2) NOT NULL,
    reason TEXT NULL,
    reference_number VARCHAR(120) NULL,
    notes TEXT NULL,
    performed_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX inventory_tx_item_idx (item_id, created_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS expenses (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'General',
    amount DECIMAL(12,2) NOT NULL,
    expense_date DATE NOT NULL,
    source VARCHAR(40) NOT NULL DEFAULT 'manual',
    inventory_item_id CHAR(36) NULL,
    inventory_transaction_id CHAR(36) NULL,
    notes TEXT NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX expenses_date_idx (facility_id, expense_date)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    entity_table VARCHAR(80) NOT NULL,
    entity_id CHAR(36) NOT NULL,
    action VARCHAR(100) NOT NULL,
    payload JSON NULL,
    actor_id CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX audit_entity_idx (entity_table, entity_id),
    INDEX audit_date_idx (facility_id, created_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS lab_branding_settings (
    facility_id CHAR(36) PRIMARY KEY,
    lab_name VARCHAR(200) NULL,
    address TEXT NULL,
    support_line VARCHAR(100) NULL,
    accreditation VARCHAR(190) NULL,
    signatory_name VARCHAR(190) NULL,
    signatory_title VARCHAR(190) NULL,
    report_footer TEXT NULL,
    updated_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS wards (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    name VARCHAR(160) NOT NULL,
    code VARCHAR(40) NOT NULL,
    ward_type VARCHAR(80) NOT NULL DEFAULT 'General',
    capacity INT NOT NULL DEFAULT 0,
    location VARCHAR(190) NULL,
    gender_restriction VARCHAR(30) NOT NULL DEFAULT 'Any',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY wards_code_key (facility_id, code)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS beds (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    ward_id CHAR(36) NOT NULL,
    bed_number VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Available',
    notes TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY beds_ward_number_key (ward_id, bed_number)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS clinical_encounters (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_number VARCHAR(50) NOT NULL UNIQUE,
    encounter_type VARCHAR(30) NOT NULL DEFAULT 'Outpatient',
    status VARCHAR(30) NOT NULL DEFAULT 'Open',
    presenting_complaint TEXT NULL,
    attending_clinician CHAR(36) NULL,
    started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ended_at DATETIME(3) NULL,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX encounters_patient_date_idx (patient_id, started_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS admissions (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NOT NULL,
    ward_id CHAR(36) NOT NULL,
    bed_id CHAR(36) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Admitted',
    admission_reason TEXT NULL,
    admitted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    discharged_at DATETIME(3) NULL,
    discharge_summary TEXT NULL,
    admitted_by CHAR(36) NULL,
    discharged_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX admissions_patient_idx (patient_id, status),
    INDEX admissions_bed_idx (bed_id, status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS vital_signs (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NOT NULL,
    temperature_c DECIMAL(4,1) NULL,
    pulse_bpm INT NULL,
    respiratory_rate INT NULL,
    systolic_bp INT NULL,
    diastolic_bp INT NULL,
    oxygen_saturation DECIMAL(5,2) NULL,
    weight_kg DECIMAL(6,2) NULL,
    height_cm DECIMAL(6,2) NULL,
    bmi DECIMAL(5,2) NULL,
    blood_glucose_mmol DECIMAL(6,2) NULL,
    pain_score INT NULL,
    notes TEXT NULL,
    measured_by CHAR(36) NULL,
    measured_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX vitals_encounter_idx (encounter_id, measured_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS clinical_notes (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NOT NULL,
    note_type VARCHAR(50) NOT NULL DEFAULT 'Clinical Presentation',
    chief_complaint TEXT NULL,
    history_of_presenting_illness TEXT NULL,
    examination TEXT NULL,
    assessment TEXT NULL,
    plan TEXT NULL,
    report_title VARCHAR(200) NULL,
    is_confidential TINYINT(1) NOT NULL DEFAULT 0,
    authored_by CHAR(36) NULL,
    authored_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX notes_encounter_idx (encounter_id, authored_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS diagnoses (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NOT NULL,
    diagnosis_name VARCHAR(250) NOT NULL,
    icd10_code VARCHAR(30) NULL,
    diagnosis_type VARCHAR(30) NOT NULL DEFAULT 'Working',
    status VARCHAR(30) NOT NULL DEFAULT 'Active',
    notes TEXT NULL,
    diagnosed_by CHAR(36) NULL,
    diagnosed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX diagnoses_encounter_idx (encounter_id, diagnosed_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS medications (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    generic_name VARCHAR(200) NOT NULL,
    brand_name VARCHAR(200) NULL,
    strength VARCHAR(80) NOT NULL,
    dosage_form VARCHAR(80) NOT NULL,
    route VARCHAR(80) NULL,
    unit VARCHAR(60) NOT NULL DEFAULT 'units',
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    quantity_on_hand DECIMAL(12,2) NOT NULL DEFAULT 0,
    reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0,
    batch_number VARCHAR(100) NULL,
    expiry_date DATE NULL,
    storage_location VARCHAR(190) NULL,
    is_controlled TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX medications_name_idx (facility_id, generic_name)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS prescriptions (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'Pending',
    notes TEXT NULL,
    prescribed_by CHAR(36) NULL,
    prescribed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    dispensed_by CHAR(36) NULL,
    dispensed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX prescriptions_patient_idx (patient_id, prescribed_at),
    INDEX prescriptions_status_idx (facility_id, status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS prescription_items (
    id CHAR(36) PRIMARY KEY,
    prescription_id CHAR(36) NOT NULL,
    medication_id CHAR(36) NULL,
    medication_name VARCHAR(250) NOT NULL,
    dose VARCHAR(100) NOT NULL,
    frequency VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    route VARCHAR(80) NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    instructions TEXT NULL,
    dispensed_quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX prescription_items_parent_idx (prescription_id)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS encounter_charges (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NULL,
    radiology_request_id CHAR(36) NULL UNIQUE,
    description VARCHAR(250) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'Clinical Service',
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'Unpaid',
    charged_by CHAR(36) NULL,
    charged_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX charges_patient_idx (patient_id, charged_at),
    INDEX charges_status_idx (facility_id, payment_status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS hospital_payments (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    charge_id CHAR(36) NOT NULL,
    patient_id CHAR(36) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(80) NOT NULL,
    reference_number VARCHAR(120) NULL,
    notes TEXT NULL,
    received_by CHAR(36) NULL,
    received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX hospital_payments_charge_idx (charge_id)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS radiology_services (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    name VARCHAR(200) NOT NULL,
    modality VARCHAR(50) NOT NULL,
    body_part VARCHAR(120) NULL,
    preparation_instructions TEXT NULL,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY radiology_service_name_key (facility_id, name)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS radiology_requests (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    request_number VARCHAR(50) NOT NULL UNIQUE,
    patient_id CHAR(36) NOT NULL,
    encounter_id CHAR(36) NULL,
    service_id CHAR(36) NOT NULL,
    clinical_indication TEXT NOT NULL,
    priority VARCHAR(30) NOT NULL DEFAULT 'Routine',
    status VARCHAR(30) NOT NULL DEFAULT 'Requested',
    scheduled_at DATETIME(3) NULL,
    requested_by CHAR(36) NULL,
    assigned_to CHAR(36) NULL,
    requested_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX radiology_patient_idx (patient_id, requested_at),
    INDEX radiology_status_idx (facility_id, status)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS radiology_reports (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    request_id CHAR(36) NOT NULL UNIQUE,
    findings TEXT NOT NULL,
    impression TEXT NOT NULL,
    recommendation TEXT NULL,
    pacs_reference TEXT NULL,
    reported_by CHAR(36) NULL,
    verified_by CHAR(36) NULL,
    reported_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    verified_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS qc_controls (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    test_id CHAR(36) NULL,
    name VARCHAR(190) NOT NULL,
    lot_number VARCHAR(100) NULL,
    level VARCHAR(80) NULL,
    expected_value VARCHAR(190) NULL,
    min_value DECIMAL(12,4) NULL,
    max_value DECIMAL(12,4) NULL,
    unit VARCHAR(80) NULL,
    expiry_date DATE NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS qc_runs (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    control_id CHAR(36) NOT NULL,
    performed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    value_numeric DECIMAL(12,4) NULL,
    value_text TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'review',
    notes TEXT NULL,
    performed_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX qc_runs_control_idx (control_id, performed_at)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS analyzers (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    name VARCHAR(190) NOT NULL,
    model VARCHAR(120) NULL,
    serial_number VARCHAR(120) NULL,
    location VARCHAR(190) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS calibration_logs (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    analyzer_id CHAR(36) NOT NULL,
    calibration_date DATE NOT NULL,
    due_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'current',
    notes TEXT NULL,
    performed_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS maintenance_logs (
    id CHAR(36) PRIMARY KEY,
    facility_id CHAR(36) NOT NULL,
    analyzer_id CHAR(36) NOT NULL,
    maintenance_date DATE NOT NULL,
    maintenance_type VARCHAR(80) NOT NULL DEFAULT 'Preventive',
    due_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    notes TEXT NULL,
    performed_by CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB`
] as const;
