import type { RadiologyRequest } from "@/types/hospital";

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatDate(value: string | null) {
  if (!value) return "Not recorded";
  return new Intl.DateTimeFormat("en-NG", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

export function buildRadiologyReportHtml(request: RadiologyRequest) {
  const report = request.radiology_reports?.[0];
  if (!report) throw new Error("This radiology report is not ready.");
  const patient = request.patients;
  const service = request.radiology_services;
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(request.request_number)} radiology report</title><style>
    @page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;background:#f8fafc;color:#0f172a;font-family:Arial,sans-serif}.page{max-width:820px;margin:auto;background:#fff;padding:30px}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #5b21b6;padding-bottom:18px}.head h1{font-size:23px;margin:0}.head p,.meta p{font-size:12px;color:#475569;margin:5px 0}.title{margin:24px 0 16px}.title h2{font-size:21px;margin:0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:20px}.panel{border:1px solid #ddd6fe;border-radius:12px;background:#faf5ff;padding:14px}.section{margin:0 0 18px;break-inside:avoid}.section h3{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#5b21b6;margin:0 0 8px}.section p{white-space:pre-wrap;font-size:13px;line-height:1.65;margin:0;border:1px solid #e2e8f0;border-radius:10px;padding:14px}.footer{border-top:1px solid #cbd5e1;margin-top:28px;padding-top:12px;color:#64748b;font-size:10px}@media print{body{background:#fff}.page{padding:0}}
  </style></head><body><main class="page"><header class="head"><div><h1>St Gianna Specialist Hospital</h1><p>No 6, 18 Road, Upper North, Transekulu, Enugu, Enugu State</p></div><p>Radiology</p></header><div class="title"><h2>Radiology report</h2></div><section class="meta"><div class="panel"><p><strong>Patient:</strong> ${escapeHtml(patient?.name || "Unknown patient")}</p><p><strong>Hospital ID:</strong> ${escapeHtml(patient?.hospital_id || patient?.lab_id || "-")}</p><p><strong>Phone:</strong> ${escapeHtml(patient?.phone || "Not recorded")}</p></div><div class="panel"><p><strong>Request:</strong> ${escapeHtml(request.request_number)}</p><p><strong>Study:</strong> ${escapeHtml([service?.name, service?.modality].filter(Boolean).join(" · ") || "Radiology study")}</p><p><strong>Reported:</strong> ${escapeHtml(formatDate(report.reported_at))}</p></div></section><section class="section"><h3>Clinical indication</h3><p>${escapeHtml(request.clinical_indication)}</p></section><section class="section"><h3>Findings</h3><p>${escapeHtml(report.findings)}</p></section><section class="section"><h3>Impression</h3><p>${escapeHtml(report.impression)}</p></section>${report.recommendation ? `<section class="section"><h3>Recommendation</h3><p>${escapeHtml(report.recommendation)}</p></section>` : ""}${report.pacs_reference ? `<section class="section"><h3>Study reference</h3><p>${escapeHtml(report.pacs_reference)}</p></section>` : ""}<footer class="footer">Generated by St Gianna Specialist Hospital.</footer></main></body></html>`;
}
